services:
  app:
    build: .
    command: 
      - /bin/bash
      - -c
      - |
        cd /api && /usr/dotnet/dotnet /api/${DOTNET_DLL} --urls=http://localhost:5050 &
        httpd-foreground
    volumes: 
      - ./api:/api
      - ./web:/usr/local/apache2/htdocs
    ports:
      - ${WEB_PORT}:80
      - ${API_PORT}:8080